name: Build, lint, and test

on: [push]

jobs:
  build:
    name: Build, lint, and test on Nodejs 

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn --ignore-engines

      - name: Build
        run: yarn build